Q.1. Introduction to Pandas: Series and DataframeTopics: What is Pandas? Series vs DataframeCreating basic structuresDemo: Create simple DataFrame manually.

In [3]:
%pip install pandas

Requirement already satisfied: pandas in c:\users\administrator\anaconda3\lib\site-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\administrator\anaconda3\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\administrator\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\administrator\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\administrator\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\administrator\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [4]:
import pandas as pd
print(pd.__version__)

2.2.2

In [9]:
numbers = pd.Series([10, 20, 30, 40, 50])
print(numbers)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [11]:
ipl_fav_teams = pd.Series(["LSG", "GT", "MI", "RCB", "DC"])
print(ipl_fav_teams)

0    LSG
1     GT
2     MI
3    RCB
4     DC
dtype: object

In [13]:
food_orders = pd.DataFrame({
    "Dish": ["Pizza", "Burger", "Biryani"],
    "Restaurents": ["Restaurent A", "Restaurent B", "Restaurent C"],
    "Price": [350, 220, 300]
})

print(food_orders)

      Dish   Restaurents  Price
0    Pizza  Restaurent A    350
1   Burger  Restaurent B    220
2  Biryani  Restaurent C    300

In [15]:
followers = pd.Series([1200, 54000, 780, 150000, 32000])
print(followers)

0      1200
1     54000
2       780
3    150000
4     32000
dtype: int64

In [17]:
songs = pd.DataFrame({
    "Songs": ["Song-A", "Song-B", "Song-C", "Song-D"],
    "Artists": ["Artist-A", "Artist-B", "Artist-C", "Artist-D"],
    "Duration": [5.10, 3.21, 4.26, 6.21]
})
print(songs)

    Songs   Artists  Duration
0  Song-A  Artist-A      5.10
1  Song-B  Artist-B      3.21
2  Song-C  Artist-C      4.26
3  Song-D  Artist-D      6.21

Q.2. Reading and Writing DataTopics:read_csvread_excelhead.taildescribe, infoExporting to CSV/ExcelDemo:Load case study dataset

In [21]:
ipl_data = pd.read_csv("matches.csv")

In [23]:
ipl_data.head()

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan

In [25]:
ipl_data.head(10)

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan
5,335987,2007/08,Jaipur,2008-04-21,League,SR Watson,Sawai Mansingh Stadium,Rajasthan Royals,Kings XI Punjab,Kings XI Punjab,bat,Rajasthan Royals,wickets,6.0,167.0,20.0,N,NaN,Aleem Dar,RB Tiffin
6,335988,2007/08,Hyderabad,2008-04-22,League,V Sehwag,"Rajiv Gandhi International Stadium, Uppal",Deccan Chargers,Delhi Daredevils,Deccan Chargers,bat,Delhi Daredevils,wickets,9.0,143.0,20.0,N,NaN,IL Howell,AM Saheba
7,335989,2007/08,Chennai,2008-04-23,League,ML Hayden,"MA Chidambaram Stadium, Chepauk",Chennai Super Kings,Mumbai Indians,Mumbai Indians,field,Chennai Super Kings,runs,6.0,209.0,20.0,N,NaN,DJ Harper,GA Pratapkumar
8,335990,2007/08,Hyderabad,2008-04-24,League,YK Pathan,"Rajiv Gandhi International Stadium, Uppal",Deccan Chargers,Rajasthan Royals,Rajasthan Royals,field,Rajasthan Royals,wickets,3.0,215.0,20.0,N,NaN,Asad Rauf,MR Benson
9,335991,2007/08,Chandigarh,2008-04-25,League,KC Sangakkara,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Mumbai Indians,Mumbai Indians,field,Kings XI Punjab,runs,66.0,183.0,20.0,N,NaN,Aleem Dar,AM Saheba

In [27]:
mobile_expense = pd.read_excel("mobile_expanses.xlsx")

In [29]:
mobile_expense.tail(3)

        Date        Expense       Category  Amount
3 2026-09-03       Cab Ride         Travel     220
4 2026-09-05  Game Purchase  Entertainment     499
5 2026-09-08      Data Pack       Recharge      79

Q.3. Selecting & Filtering Data (loc & iloc)Topics:Selecting rows, columnsBoolean conditionsQuerying dataDemo:Select customers with revenue > 10000.

In [11]:
movie_data = pd.read_csv("movies_metadata.csv", low_memory=False)

movie_data.columns.tolist()

['adult',
 'belongs_to_collection',
 'budget',
 'genres',
 'homepage',
 'id',
 'imdb_id',
 'original_language',
 'original_title',
 'overview',
 'popularity',
 'poster_path',
 'production_companies',
 'production_countries',
 'release_date',
 'revenue',
 'runtime',
 'spoken_languages',
 'status',
 'tagline',
 'title',
 'video',
 'vote_average',
 'vote_count']

In [13]:
movie_data.loc[:, ["title", "vote_average"]]

                             title  vote_average
0                        Toy Story           7.7
1                          Jumanji           6.9
2                 Grumpier Old Men           6.5
3                Waiting to Exhale           6.1
4      Father of the Bride Part II           5.7
...                            ...           ...
45461                       Subdue           4.0
45462          Century of Birthing           9.0
45463                     Betrayal           3.8
45464             Satan Triumphant           0.0
45465                     Queerama           0.0

[45466 rows x 2 columns]

In [15]:
flipkart_products = pd.DataFrame({
    "product_name": [
        "Laptop",
        "Smartphone",
        "Headphones",
        "Keyboard",
        "Mouse",
        "Smartwatch",
        "Tablet",
        "Monitor",
        "Power Bank",
        "Speaker",
        "Webcam",
        "Printer"
    ],
    "category": [
        "Electronics",
        "Electronics",
        "Accessories",
        "Accessories",
        "Accessories",
        "Electronics",
        "Electronics",
        "Electronics",
        "Accessories",
        "Electronics",
        "Accessories",
        "Electronics"
    ],
    "price": [
        55000,
        25000,
        2500,
        1500,
        800,
        4000,
        18000,
        12000,
        1500,
        3000,
        2200,
        9000
    ]
})

flipkart_products

   product_name     category  price
0        Laptop  Electronics  55000
1    Smartphone  Electronics  25000
2    Headphones  Accessories   2500
3      Keyboard  Accessories   1500
4         Mouse  Accessories    800
5    Smartwatch  Electronics   4000
6        Tablet  Electronics  18000
7       Monitor  Electronics  12000
8    Power Bank  Accessories   1500
9       Speaker  Electronics   3000
10       Webcam  Accessories   2200
11      Printer  Electronics   9000

In [19]:
flipkart_products.iloc[0:10,:]

  product_name     category  price
0       Laptop  Electronics  55000
1   Smartphone  Electronics  25000
2   Headphones  Accessories   2500
3     Keyboard  Accessories   1500
4        Mouse  Accessories    800
5   Smartwatch  Electronics   4000
6       Tablet  Electronics  18000
7      Monitor  Electronics  12000
8   Power Bank  Accessories   1500
9      Speaker  Electronics   3000

In [21]:
zomato_orders = pd.DataFrame({
    "restaurant": [
        "Pizza Hut",
        "Dominos",
        "McDonalds",
        "Burger King",
        "Biryani House",
        "Subway"
    ],
    
    "order_amount": [
        350,
        750,
        280,
        900,
        650,
        420
    ],
    
    "delivery_time": [
        30,
        45,
        25,
        50,
        40,
        35
    ]
})

zomato_orders

      restaurant  order_amount  delivery_time
0      Pizza Hut           350             30
1        Dominos           750             45
2      McDonalds           280             25
3    Burger King           900             50
4  Biryani House           650             40
5         Subway           420             35

In [23]:
zomato_orders["order_amount"] > 500

0    False
1     True
2    False
3     True
4     True
5    False
Name: order_amount, dtype: bool

In [27]:
zomato_orders[zomato_orders["order_amount"] > 500]

      restaurant  order_amount  delivery_time
1        Dominos           750             45
3    Burger King           900             50
4  Biryani House           650             40

In [29]:
spotify_songs = pd.DataFrame({
    "song": [
        "Song A",
        "Song B",
        "Song C",
        "Song D",
        "Song E",
        "Song F"
    ],
    
    "artist": [
        "Artist 1",
        "Artist 2",
        "Artist 3",
        "Artist 4",
        "Artist 5",
        "Artist 6"
    ],
    
    "streams": [
        1500000,
        850000,
        2200000,
        1200000,
        600000,
        3100000
    ],
    
    "duration": [
        170,
        160,
        210,
        175,
        140,
        165
    ]
})

spotify_songs

     song    artist  streams  duration
0  Song A  Artist 1  1500000       170
1  Song B  Artist 2   850000       160
2  Song C  Artist 3  2200000       210
3  Song D  Artist 4  1200000       175
4  Song E  Artist 5   600000       140
5  Song F  Artist 6  3100000       165

In [31]:
spotify_songs.query("streams > 1000000 and duration < 180")

     song    artist  streams  duration
0  Song A  Artist 1  1500000       170
3  Song D  Artist 4  1200000       175
5  Song F  Artist 6  3100000       165

In [33]:
ipl_matches = pd.DataFrame({
    "team1": [
        "CSK",
        "MI",
        "RCB",
        "KKR",
        "RR",
        "DC"
    ],

    "team2": [
        "MI",
        "RCB",
        "KKR",
        "SRH",
        "CSK",
        "PBKS"
    ],

    "winner": [
        "CSK",
        "MI",
        "RCB",
        "KKR",
        "CSK",
        "PBKS"
    ],

    "total_runs": [
        325,
        410,
        280,
        365,
        430,
        295
    ]
})

ipl_matches

  team1 team2 winner  total_runs
0   CSK    MI    CSK         325
1    MI   RCB     MI         410
2   RCB   KKR    RCB         280
3   KKR   SRH    KKR         365
4    RR   CSK    CSK         430
5    DC  PBKS   PBKS         295

In [35]:
ipl_matches["total_runs"] < 300

0    False
1    False
2     True
3    False
4    False
5     True
Name: total_runs, dtype: bool

In [37]:
ipl_matches[ipl_matches["total_runs"] < 300]

  team1 team2 winner  total_runs
2   RCB   KKR    RCB         280
5    DC  PBKS   PBKS         295

Q.4. Sorting and ReindexingtTopics:sort_valuessort_IndexReset IndexReIndexDemo:Sort products by price descending.

In [6]:
movies = pd.DataFrame({
    "title": [
        "3 Idiots",
        "Dangal",
        "PK",
        "Lagaan",
        "Taare Zameen Par",
        "Bajrangi Bhaijaan"
    ],

    "rating": [
        8.4,
        8.3,
        8.1,
        8.1,
        8.3,
        8.1
    ],

    "release_year": [
        2009,
        2016,
        2014,
        2001,
        2007,
        2015
    ]
})

movies

               title  rating  release_year
0           3 Idiots     8.4          2009
1             Dangal     8.3          2016
2                 PK     8.1          2014
3             Lagaan     8.1          2001
4   Taare Zameen Par     8.3          2007
5  Bajrangi Bhaijaan     8.1          2015

In [8]:
movies.sort_values(by="rating", ascending=False)

               title  rating  release_year
0           3 Idiots     8.4          2009
1             Dangal     8.3          2016
4   Taare Zameen Par     8.3          2007
2                 PK     8.1          2014
3             Lagaan     8.1          2001
5  Bajrangi Bhaijaan     8.1          2015

In [10]:
ipl_teams = pd.DataFrame({
    "Teams": ["CSK", "MI", "RCB", "KKR", "RR", "SRH", "LSG", "DC", "GT", "PBKS"],
    "Points": [18, 16, 16, 14, 10, 9, 8, 8, 4, 2],
    "Net_Run_Rate": [0.652, 0.489, 0.312, 0.105, -0.120, -0.340, 0.965, -0.253, 0.536, -1.256]
})
ipl_teams

  Teams  Points  Net_Run_Rate
0   CSK      18         0.652
1    MI      16         0.489
2   RCB      16         0.312
3   KKR      14         0.105
4    RR      10        -0.120
5   SRH       9        -0.340
6   LSG       8         0.965
7    DC       8        -0.253
8    GT       4         0.536
9  PBKS       2        -1.256

In [12]:
ipl_teams.sort_index(ascending=False)

  Teams  Points  Net_Run_Rate
9  PBKS       2        -1.256
8    GT       4         0.536
7    DC       8        -0.253
6   LSG       8         0.965
5   SRH       9        -0.340
4    RR      10        -0.120
3   KKR      14         0.105
2   RCB      16         0.312
1    MI      16         0.489
0   CSK      18         0.652

In [24]:
youtube_videos = pd.DataFrame({
    "Title": ["Tutorial", "Vlog", "Game Throughs", "Roasting", "Movie Clips", "Stand up Comedy"],
    "Views": [250000, 1000, 30000, 6000000, 32, 4659],
    "Likes": [3000, 30, 10000, 5000, 32, 3]
}, index=[10, 20, 30, 40, 50, 60])

youtube_videos

              Title    Views  Likes
10         Tutorial   250000   3000
20             Vlog     1000     30
30    Game Throughs    30000  10000
40         Roasting  6000000   5000
50      Movie Clips       32     32
60  Stand up Comedy     4659      3

In [26]:
youtube_videos.reset_index(drop=True)

             Title    Views  Likes
0         Tutorial   250000   3000
1             Vlog     1000     30
2    Game Throughs    30000  10000
3         Roasting  6000000   5000
4      Movie Clips       32     32
5  Stand up Comedy     4659      3

In [28]:
restaurants = pd.DataFrame({
    "restaurant": [
        "Dominos",
        "Pizza Hut",
        "McDonalds",
        "Burger King",
        "Biryani House"
    ],
    
    "rating": [
        4.2,
        4.1,
        4.0,
        4.3,
        4.5
    ]
})

restaurants

      restaurant  rating
0        Dominos     4.2
1      Pizza Hut     4.1
2      McDonalds     4.0
3    Burger King     4.3
4  Biryani House     4.5

In [30]:
restaurants.reindex([4,0,1,2,3])

      restaurant  rating
4  Biryani House     4.5
0        Dominos     4.2
1      Pizza Hut     4.1
2      McDonalds     4.0
3    Burger King     4.3

In [32]:
flipkart_discount = pd.DataFrame({
    "product_name": [
        "Laptop",
        "Smartphone",
        "Headphones",
        "Smartwatch",
        "Power Bank",
        "Keyboard"
    ],

    "price": [
        55000,
        25000,
        2500,
        4000,
        1500,
        1800
    ],

    "discount": [
        10,
        25,
        40,
        15,
        35,
        20
    ]
})

flipkart_discount

  product_name  price  discount
0       Laptop  55000        10
1   Smartphone  25000        25
2   Headphones   2500        40
3   Smartwatch   4000        15
4   Power Bank   1500        35
5     Keyboard   1800        20

In [34]:
flipkart_discount.sort_values(by='discount', ascending=False)

  product_name  price  discount
2   Headphones   2500        40
4   Power Bank   1500        35
1   Smartphone  25000        25
5     Keyboard   1800        20
3   Smartwatch   4000        15
0       Laptop  55000        10

In [36]:
flipkart_discount.sort_values(by='discount', ascending=False).reset_index(drop=True)

  product_name  price  discount
0   Headphones   2500        40
1   Power Bank   1500        35
2   Smartphone  25000        25
3     Keyboard   1800        20
4   Smartwatch   4000        15
5       Laptop  55000        10

Q.5. Handling Missing ValuesTopics:Isnulldropnafillnareplace missing with median / meanDemo:Clean missing ages in a customer dataset

In [40]:
ipl_players = pd.read_csv("Fantasy_points_Dream11.csv")

ipl_players.columns.tolist()

['Player',
 'Team',
 'AGE',
 'Role',
 'Special Feature',
 'Match_1',
 'Match_2',
 'Match_3',
 'Match_4',
 'Match_5',
 'Match_6',
 'Match_7',
 'Match_8',
 'Match_9',
 'Match_10',
 'Match_11',
 'Match_12',
 'Match_13',
 'Match_14']

Q.6. Handling Duplicates & OutliersTopics:drop_duplicatesIQR methodZ-score conceptDemo:Detect outlier sales values